# https://travis-ci.org/#!/phlax/debian-criu

install:
  - make debs

script:
  - ls

before_deploy:
  - echo $DOCKER_API_TOKEN | docker login -u phlax --password-stdin

deploy:
  provider: script
  script: make hub-image
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(masterXXX)$
