# https://travis-ci.org/#!/phlax/debian-criu

install:
  - make debs
  - apt install -y -qq reprepro

script:
  - ls build
  - make install-test

deploy:
  provider: script
  script: make publish
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master)$
